CREATE TABLE PAGEVIEWS_PER_HOUR
WITH (
    KAFKA_TOPIC = 'pageviews_per_hour',
    PARTITIONS = 1,
    VALUE_FORMAT = 'AVRO'
    )
AS SELECT
  P.PAGEID PAGEID,
  COUNT(*) VIEW_COUNT,
  FROM_UNIXTIME(WINDOWSTART) AS WINDOW_START,
  FROM_UNIXTIME(WINDOWEND) AS WINDOW_END
FROM PAGEVIEWS P
WINDOW TUMBLING (SIZE 1 HOUR, GRACE PERIOD 1 MINUTE)
GROUP BY P.PAGEID
EMIT CHANGES;
